springproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('startspring.urls')),
]

startspring/urls.py
from django.urls import path
from .views import  Contact, SpringList, QualityExp, Ranking
from . import views

app_name = 'appname'
urlpatterns = [
    path('startspring/', views.startspring , name='spring_search'),
    path('startspring/contact.html', Contact.as_view()),
    path('startspring/springlist.html', SpringList.as_view()),
    path('startspring/qualityexp.html', QualityExp.as_view()),
    path('startspring/ranking.html', Ranking.as_view()),
    path('startspring/prefecture/', views.prefecture, name='prefecture'),
    path('startspring/prefecture/spring_each/', views.spring_each, name='springs'),
    path('startspring/search/', views.spring_search, name="search"),
]

startspring/models.py
from django.db import models

# Create your models here.

startspring/views.py
from typing import Any
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import TemplateView   
import sys,  pykakasi
sys.path.append("C:\\Users\\Owner\\python_practice\\springproject\\startspring")
from ranking_get import Ranking_get
from arrange_spring import Arrange_spring



#一番初めのページへの遷移
def startspring(request):
    #リクエストがあった→温泉検索が行われた
    if request.method == "POST":
        #温泉検索で入力された温泉名をローマ字に変換
        spring_get = request.POST.get('search')
        kakasi = pykakasi.kakasi()
        kakasi.setMode('J', 'a')
        kakasi.setMode('K', 'a')
        kakasi.setMode('H', 'a')
        conversion = kakasi.getConverter()
        spring_get = conversion.do(spring_get)
        
        #全ての温泉のhtmlの名前に変換したものをリストとして保持する
        all_spring = Arrange_spring()
        all_spring_get = all_spring.same_judge #温泉のhtml名を取得
        all_spring_nameset = all_spring.name_set #温泉の名前と県のひとかたまりをkeyとした辞書を取得
        
        match = []

        same_search = {}

        #入力された温泉名が用意されている温泉名の一部において一致するものがあればmatchに格納していく
        for each_spring in all_spring_get:
            if spring_get in each_spring:
                match.append(each_spring)

        #matchの要素が1つであれば、そのままmatchの要素(html名)を持ちいてhtmlを表示する
        if len(match) == 1:
            return render(request, 'spring_each/'+match[0]+".html")
        elif len(match) == 0:#matchの要素が0であれば、検索結果に該当するものが無いことを示すhtmlを表示する
            return render(request, 'spring_noexit.html')
        else: #matchの要素が複数あれば、ユーザーに選択されるページのhtmlを表示する
            for each_spring in match:
                for key, value in all_spring_nameset.items():
                    if each_spring == value:
                        same_search[key] = value
            context = {
                'same_search': same_search,
            }
            return render(request, 'search-spring.html', context)
    else:#リクエストがなければ、start.htmlを表示する
        return render(request, 'start.html')

#contact.htmlを表示する
class Contact(TemplateView):
    template_name = 'contact.html'

#springlist.htmlを表示する
class SpringList(TemplateView):
    template_name = 'springlist.html'

#qualityexp.htmlを表示する
class QualityExp(TemplateView):
    template_name = 'qualityexp.html'

#ranking.htmlを表示する
class Ranking(TemplateView):
    template_name = 'ranking.html'

    #それぞれのランキングのファイルの情報を取得してranking.htmlに送る
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)

        information = []

        inf = Ranking_get("total_rank.csv")
        inf.list_get()

        inf_atmos = Ranking_get("atmos_rank.csv")
        inf_atmos.list_get()

        inf_food = Ranking_get("food_rank.csv")
        inf_food.list_get()

        inf_quality = Ranking_get("quality_rank.csv")
        inf_quality.list_get()

        #それぞれのランキングを一次元配列として格納
        information = inf.ranking_inf + inf_atmos.ranking_inf + inf_food.ranking_inf + inf_quality.ranking_inf

        context["tweets"] = information
        return context

#springlistから情報を与えられ、それに応じたhtmlを返す関数
def prefecture(request):
    #kakasiは与えられた情報をローマ字に変換するため
    kakasi = pykakasi.kakasi()
    kakasi.setMode('J', 'a')
    conversion = kakasi.getConverter()
    var1 = request.POST.get('id1')
    pref = conversion.do(var1)

    return render(request, 'prefectures/'+pref+".html")  

#それぞれの温泉のhtmlを表示する(都道府県からの遷移)
def spring_each(request):
    spring_name = request.POST.get('id2')
    return render(request, 'spring_each/'+spring_name+".html")

#それぞれの温泉のhtmlを表示する(温泉検索で該当が複数あった場合の遷移)
def spring_search(request):
    each_search = request.POST.get('id3')
    return render(request, 'spring_each/'+each_search+".html")
    

templates/prefectures/fukuoka.html
{% extends 'base-prefecture.html' %}

{% block header %}

{% endblock header %}

{% block content %}

<h2 class="icon">福岡県</h2><form action="{% url 'appname:springs' %}" method="post" name="haratsuruonsen_harazuru_fukuoka">
{% csrf_token %}<input name="id2" type="hidden" value="haratsuruonsen_harazuru_fukuoka"/><div class="con"><a href="./spring_each/" onclick="document.haratsuruonsen_harazuru_fukuoka.submit(); return false;"><img class="spring_img" src="https://static.yukoyuko.net/images/onsen/onsen_0628_0001.jpg"/></a><p>原鶴温泉</p></div></form><form action="{% url 'appname:springs' %}" method="post" name="chikugokawaonsen_chikugogawa_fukuoka">
{% csrf_token %}<input name="id2" type="hidden" value="chikugokawaonsen_chikugogawa_fukuoka"/><div class="con"><a href="./spring_each/" onclick="document.chikugokawaonsen_chikugogawa_fukuoka.submit(); return false;"><img class="spring_img" src="https://static.yukoyuko.net/images/onsen/onsen_0626_0001.jpg"/></a><p>筑後川温泉</p></div></form><form action="{% url 'appname:springs' %}" method="post" name="futsukaichionsen_futsukaichi_fukuoka">
{% csrf_token %}<input name="id2" type="hidden" value="futsukaichionsen_futsukaichi_fukuoka"/><div class="con"><a href="./spring_each/" onclick="document.futsukaichionsen_futsukaichi_fukuoka.submit(); return false;"><img class="spring_img" src="https://static.yukoyuko.net/images/onsen/onsen_0629_0001.jpg"/></a><p>二日市温泉</p></div></form><form action="{% url 'appname:springs' %}" method="post" name="genkaisatsukionsen_genkaisatsuki_fukuoka">
{% csrf_token %}<input name="id2" type="hidden" value="genkaisatsukionsen_genkaisatsuki_fukuoka"/><div class="con"><a href="./spring_each/" onclick="document.genkaisatsukionsen_genkaisatsuki_fukuoka.submit(); return false;"><img class="spring_img" src="https://static.yukoyuko.net/images/onsen/onsen_0949_0001.jpg"/></a><p>玄海さつき温泉</p></div></form><form action="{% url 'appname:springs' %}" method="post" name="kurokionsen_kuroki_fukuoka">
{% csrf_token %}<input name="id2" type="hidden" value="kurokionsen_kuroki_fukuoka"/><div class="con"><a href="./spring_each/" onclick="document.kurokionsen_kuroki_fukuoka.submit(); return false;"><img class="spring_img" src="https://static.yukoyuko.net/images/onsen/onsen_1153_0001.jpg"/></a><p>黒木温泉</p></div></form><form action="{% url 'appname:springs' %}" method="post" name="hoshinoonsen_hoshino_fukuoka">
{% csrf_token %}<input name="id2" type="hidden" value="hoshinoonsen_hoshino_fukuoka"/><div class="con"><a href="./spring_each/" onclick="document.hoshinoonsen_hoshino_fukuoka.submit(); return false;"><img class="spring_img" src="https://static.yukoyuko.net/images/onsen/onsen_1537_0001.jpg"/></a><p>星野温泉</p></div></form><form action="{% url 'appname:springs' %}" method="post" name="yakuouteraonsen_yakuouji_fukuoka">
{% csrf_token %}<input name="id2" type="hidden" value="yakuouteraonsen_yakuouji_fukuoka"/><div class="con"><a href="./spring_each/" onclick="document.yakuouteraonsen_yakuouji_fukuoka.submit(); return false;"><img class="spring_img" src="https://static.yukoyuko.net/images/onsen/onsen_0488_0001.jpg"/></a><p>薬王寺温泉</p></div></form><form action="{% url 'appname:springs' %}" method="post" name="hachimanonsen_yahata_fukuoka">
{% csrf_token %}<input name="id2" type="hidden" value="hachimanonsen_yahata_fukuoka"/><div class="con"><a href="./spring_each/" onclick="document.hachimanonsen_yahata_fukuoka.submit(); return false;"><img class="spring_img" src="https://static.yukoyuko.net/images/onsen/onsen_1165_0001.jpg"/></a><p>八幡温泉</p></div></form><form action="{% url 'appname:springs' %}" method="post" name="yoshiionsen_yoshii_fukuoka">
{% csrf_token %}<input name="id2" type="hidden" value="yoshiionsen_yoshii_fukuoka"/><div class="con"><a href="./spring_each/" onclick="document.yoshiionsen_yoshii_fukuoka.submit(); return false;"><img class="spring_img" src="https://static.yukoyuko.net/images/onsen/onsen_0631_0001.jpg"/></a><p>吉井温泉</p></div></form><form action="{% url 'appname:springs' %}" method="post" name="hachimanhimawarionsen_yahatahimawari_fukuoka">
{% csrf_token %}<input name="id2" type="hidden" value="hachimanhimawarionsen_yahatahimawari_fukuoka"/><div class="con"><a href="./spring_each/" onclick="document.hachimanhimawarionsen_yahatahimawari_fukuoka.submit(); return false;"><img class="spring_img" src="https://static.yukoyuko.net/images/onsen/onsen_0950_0001.jpg"/></a><p>八幡ひまわり温泉</p></div></form><form action="{% url 'appname:springs' %}" method="post" name="wakitaonsen_wakita_fukuoka">
{% csrf_token %}<input name="id2" type="hidden" value="wakitaonsen_wakita_fukuoka"/><div class="con"><a href="./spring_each/" onclick="document.wakitaonsen_wakita_fukuoka.submit(); return false;"><img class="spring_img" src="https://static.yukoyuko.net/images/onsen/onsen_1032_0001.jpg"/></a><p>脇田温泉</p></div></form><form action="{% url 'appname:springs' %}" method="post" name="hisayamaonsen_hisayama_fukuoka">
{% csrf_token %}<input name="id2" type="hidden" value="hisayamaonsen_hisayama_fukuoka"/><div class="con"><a href="./spring_each/" onclick="document.hisayamaonsen_hisayama_fukuoka.submit(); return false;"><img class="spring_img" src="https://static.yukoyuko.net/images/onsen/onsen_1541_0001.jpg"/></a><p>久山温泉</p></div></form><form action="{% url 'appname:springs' %}" method="post" name="akizukionsen_akizuki_fukuoka">
{% csrf_token %}<input name="id2" type="hidden" value="akizukionsen_akizuki_fukuoka"/><div class="con"><a href="./spring_each/" onclick="document.akizukionsen_akizuki_fukuoka.submit(); return false;"><img class="spring_img" src="https://static.yukoyuko.net/images/onsen/onsen_1611_0001.jpg"/></a><p>秋月温泉</p></div></form><form action="{% url 'appname:springs' %}" method="post" name="hidehikoyamaonsen_hikosan_fukuoka">
{% csrf_token %}<input name="id2" type="hidden" value="hidehikoyamaonsen_hikosan_fukuoka"/><div class="con"><a href="./spring_each/" onclick="document.hidehikoyamaonsen_hikosan_fukuoka.submit(); return false;"><img class="spring_img" src="https://static.yukoyuko.net/images/onsen/onsen_1992_0001.jpg"/></a><p>英彦山温泉</p></div></form>
{% endblock content %}

templates/prefectures/ibaraki.html
{% extends 'base-prefecture.html' %}

{% block header %}

{% endblock header %}

{% block content %}

<h2 class="icon">茨城県</h2><form action="{% url 'appname:springs' %}" method="post" name="tsukubasanonsen_tsukubasan_ibaraki">
{% csrf_token %}<input name="id2" type="hidden" value="tsukubasanonsen_tsukubasan_ibaraki"/><div class="con"><a href="./spring_each/" onclick="document.tsukubasanonsen_tsukubasan_ibaraki.submit(); return false;"><img class="spring_img" src="https://static.yukoyuko.net/images/onsen/onsen_1051_0001.jpg"/></a><p>筑波山温泉</p></div></form><form action="{% url 'appname:springs' %}" method="post" name="oogoonsen_daigo_ibaraki">
{% csrf_token %}<input name="id2" type="hidden" value="oogoonsen_daigo_ibaraki"/><div class="con"><a href="./spring_each/" onclick="document.oogoonsen_daigo_ibaraki.submit(); return false;"><img class="spring_img" src="https://static.yukoyuko.net/images/onsen/onsen_0261_0001.jpg"/></a><p>大子温泉</p></div></form><form action="{% url 'appname:springs' %}" method="post" name="fukurodaonsen_fukuroda_ibaraki">
{% csrf_token %}<input name="id2" type="hidden" value="fukurodaonsen_fukuroda_ibaraki"/><div class="con"><a href="./spring_each/" onclick="document.fukurodaonsen_fukuroda_ibaraki.submit(); return false;"><img class="spring_img" src="https://static.yukoyuko.net/images/onsen/onsen_0262_0001.jpg"/></a><p>袋田温泉</p></div></form><form action="{% url 'appname:springs' %}" method="post" name="ooaraionsen_ooarai_ibaraki">
{% csrf_token %}<input name="id2" type="hidden" value="ooaraionsen_ooarai_ibaraki"/><div class="con"><a href="./spring_each/" onclick="document.ooaraionsen_ooarai_ibaraki.submit(); return false;"><img class="spring_img" src="https://static.yukoyuko.net/images/onsen/onsen_1149_0001.jpg"/></a><p>大洗温泉</p></div></form><form action="{% url 'appname:springs' %}" method="post" name="tsukubaonsen_tsukuba_ibaraki">
{% csrf_token %}<input name="id2" type="hidden" value="tsukubaonsen_tsukuba_ibaraki"/><div class="con"><a href="./spring_each/" onclick="document.tsukubaonsen_tsukuba_ibaraki.submit(); return false;"><img class="spring_img" src="https://static.yukoyuko.net/images/onsen/onsen_0186_0001.jpg"/></a><p>筑波温泉</p></div></form><form action="{% url 'appname:springs' %}" method="post" name="itsuuraonsen_itsuura_ibaraki">
{% csrf_token %}<input name="id2" type="hidden" value="itsuuraonsen_itsuura_ibaraki"/><div class="con"><a href="./spring_each/" onclick="document.itsuuraonsen_itsuura_ibaraki.submit(); return false;"><img class="spring_img" src="https://static.yukoyuko.net/images/onsen/onsen_0836_0001.jpg"/></a><p>五浦温泉</p></div></form><form action="{% url 'appname:springs' %}" method="post" name="yokokawaonsen_yokokawa_ibaraki">
{% csrf_token %}<input name="id2" type="hidden" value="yokokawaonsen_yokokawa_ibaraki"/><div class="con"><a href="./spring_each/" onclick="document.yokokawaonsen_yokokawa_ibaraki.submit(); return false;"><img class="spring_img" src="https://static.yukoyuko.net/images/onsen/onsen_1552_0001.jpg"/></a><p>横川温泉</p></div></form><form action="{% url 'appname:springs' %}" method="post" name="isoharaonsen_isohara_ibaraki">
{% csrf_token %}<input name="id2" type="hidden" value="isoharaonsen_isohara_ibaraki"/><div class="con"><a href="./spring_each/" onclick="document.isoharaonsen_isohara_ibaraki.submit(); return false;"><img class="spring_img" src="https://static.yukoyuko.net/images/onsen/onsen_0260_0001.jpg"/></a><p>磯原温泉</p></div></form><form action="{% url 'appname:springs' %}" method="post" name="hirakataminatoonsen_hiragata_ibaraki">
{% csrf_token %}<input name="id2" type="hidden" value="hirakataminatoonsen_hiragata_ibaraki"/><div class="con"><a href="./spring_each/" onclick="document.hirakataminatoonsen_hiragata_ibaraki.submit(); return false;"><img class="spring_img" src="https://static.yukoyuko.net/images/onsen/onsen_0825_0001.jpg"/></a><p>平潟港温泉</p></div></form><form action="{% url 'appname:springs' %}" method="post" name="isozakionsen_isozaki_ibaraki">
{% csrf_token %}<input name="id2" type="hidden" value="isozakionsen_isozaki_ibaraki"/><div class="con"><a href="./spring_each/" onclick="document.isozakionsen_isozaki_ibaraki.submit(); return false;"><img class="spring_img" src="https://static.yukoyuko.net/images/onsen/onsen_1681_0001.jpg"/></a><p>いそざき温泉</p></div></form>
{% endblock content %}

templates/prefectures/kagawa.html
{% extends 'base-prefecture.html' %}

{% block header %}

{% endblock header %}

{% block content %}

<h2 class="icon">香川県</h2><form action="{% url 'appname:springs' %}" method="post" name="konpiraonsensato_konpira_kagawa">
{% csrf_token %}<input name="id2" type="hidden" value="konpiraonsensato_konpira_kagawa"/><div class="con"><a href="./spring_each/" onclick="document.konpiraonsensato_konpira_kagawa.submit(); return false;"><img class="spring_img" src="https://static.yukoyuko.net/images/onsen/onsen_0780_0001.jpg"/></a><p>こんぴら温泉郷</p></div></form><form action="{% url 'appname:springs' %}" method="post" name="shionoeonsen_shionoe_kagawa">
{% csrf_token %}<input name="id2" type="hidden" value="shionoeonsen_shionoe_kagawa"/><div class="con"><a href="./spring_each/" onclick="document.shionoeonsen_shionoe_kagawa.submit(); return false;"><img class="spring_img" src="https://static.yukoyuko.net/images/onsen/onsen_0319_0001.jpg"/></a><p>塩江温泉</p></div></form><form action="{% url 'appname:springs' %}" method="post" name="shouzushimaonsen_shoudoshima_kagawa">
{% csrf_token %}<input name="id2" type="hidden" value="shouzushimaonsen_shoudoshima_kagawa"/><div class="con"><a href="./spring_each/" onclick="document.shouzushimaonsen_shoudoshima_kagawa.submit(); return false;"><img class="spring_img" src="https://static.yukoyuko.net/images/onsen/onsen_0072_0001.jpg"/></a><p>小豆島温泉</p></div></form><form action="{% url 'appname:springs' %}" method="post" name="ajionsen_aji_kagawa">
{% csrf_token %}<input name="id2" type="hidden" value="ajionsen_aji_kagawa"/><div class="con"><a href="./spring_each/" onclick="document.ajionsen_aji_kagawa.submit(); return false;"><img class="spring_img" src="https://static.yukoyuko.net/images/onsen/onsen_0317_0001.jpg"/></a><p>あじ温泉</p></div></form><form action="{% url 'appname:springs' %}" method="post" name="setooohashionsen_setooohashi_kagawa">
{% csrf_token %}<input name="id2" type="hidden" value="setooohashionsen_setooohashi_kagawa"/><div class="con"><a href="./spring_each/" onclick="document.setooohashionsen_setooohashi_kagawa.submit(); return false;"><img class="spring_img" src="https://static.yukoyuko.net/images/onsen/onsen_0938_0001.jpg"/></a><p>瀬戸大橋温泉</p></div></form>
{% endblock content %}

templates/prefectures/kouchi.html
{% extends 'base-prefecture.html' %}

{% block header %}

{% endblock header %}

{% block content %}

<h2 class="icon">高知県</h2><form action="{% url 'appname:springs' %}" method="post" name="ashizurionsensato_ashizuri_kouchi">
{% csrf_token %}<input name="id2" type="hidden" value="ashizurionsensato_ashizuri_kouchi"/><div class="con"><a href="./spring_each/" onclick="document.ashizurionsensato_ashizuri_kouchi.submit(); return false;"><img class="spring_img" src="https://static.yukoyuko.net/images/onsen/onsen_0893_0001.jpg"/></a><p>あしずり温泉郷</p></div></form><form action="{% url 'appname:springs' %}" method="post" name="sansuisonoonsen_sansuien_kouchi">
{% csrf_token %}<input name="id2" type="hidden" value="sansuisonoonsen_sansuien_kouchi"/><div class="con"><a href="./spring_each/" onclick="document.sansuisonoonsen_sansuien_kouchi.submit(); return false;"><img class="spring_img" src="https://static.yukoyuko.net/images/onsen/onsen_1124_0001.jpg"/></a><p>三翠園温泉</p></div></form><form action="{% url 'appname:springs' %}" method="post" name="yosakoionsen_yosakoi_kouchi">
{% csrf_token %}<input name="id2" type="hidden" value="yosakoionsen_yosakoi_kouchi"/><div class="con"><a href="./spring_each/" onclick="document.yosakoionsen_yosakoi_kouchi.submit(); return false;"><img class="spring_img" src="https://static.yukoyuko.net/images/onsen/onsen_1309_0001.jpg"/></a><p>よさこい温泉</p></div></form><form action="{% url 'appname:springs' %}" method="post" name="tosaryuuonsen_tosaryuu_kouchi">
{% csrf_token %}<input name="id2" type="hidden" value="tosaryuuonsen_tosaryuu_kouchi"/><div class="con"><a href="./spring_each/" onclick="document.tosaryuuonsen_tosaryuu_kouchi.submit(); return false;"><img class="spring_img" src="https://static.yukoyuko.net/images/onsen/onsen_1342_0001.jpg"/></a><p>土佐龍温泉</p></div></form><form action="{% url 'appname:springs' %}" method="post" name="youionsen_mochii_kouchi">
{% csrf_token %}<input name="id2" type="hidden" value="youionsen_mochii_kouchi"/><div class="con"><a href="./spring_each/" onclick="document.youionsen_mochii_kouchi.submit(); return false;"><img class="spring_img" src="https://static.yukoyuko.net/images/onsen/onsen_1583_0001.jpg"/></a><p>用井温泉</p></div></form><form action="{% url 'appname:springs' %}" method="post" name="befukyouonsen_befukyou_kouchi">
{% csrf_token %}<input name="id2" type="hidden" value="befukyouonsen_befukyou_kouchi"/><div class="con"><a href="./spring_each/" onclick="document.befukyouonsen_befukyou_kouchi.submit(); return false;"><img class="spring_img" src="https://static.yukoyuko.net/images/onsen/onsen_0424_0001.jpg"/></a><p>べふ峡温泉</p></div></form>
{% endblock content %}

templates/prefectures/oosakafu.html
{% extends 'base-prefecture.html' %}

{% block header %}

{% endblock header %}

{% block content %}

<h2 class="icon">大阪府</h2><form action="{% url 'appname:springs' %}" method="post" name="ishikirionsen_ishikiri_oosakafu">
{% csrf_token %}<input name="id2" type="hidden" value="ishikirionsen_ishikiri_oosakafu"/><div class="con"><a href="./spring_each/" onclick="document.ishikirionsen_ishikiri_oosakafu.submit(); return false;"><img class="spring_img" src="https://static.yukoyuko.net/images/onsen/onsen_0863_0001.jpg"/></a><p>石切温泉</p></div></form><form action="{% url 'appname:springs' %}" method="post" name="inunakiyamaonsen_inunakiyama_oosakafu">
{% csrf_token %}<input name="id2" type="hidden" value="inunakiyamaonsen_inunakiyama_oosakafu"/><div class="con"><a href="./spring_each/" onclick="document.inunakiyamaonsen_inunakiyama_oosakafu.submit(); return false;"><img class="spring_img" src="https://static.yukoyuko.net/images/onsen/onsen_1018_0001.jpg"/></a><p>犬鳴山温泉</p></div></form><form action="{% url 'appname:springs' %}" method="post" name="kankuuonsen_kankuu_oosakafu">
{% csrf_token %}<input name="id2" type="hidden" value="kankuuonsen_kankuu_oosakafu"/><div class="con"><a href="./spring_each/" onclick="document.kankuuonsen_kankuu_oosakafu.submit(); return false;"><img class="spring_img" src="https://static.yukoyuko.net/images/onsen/onsen_1156_0001.jpg"/></a><p>関空温泉</p></div></form><form action="{% url 'appname:springs' %}" method="post" name="fukuoonsen_fushio_oosakafu">
{% csrf_token %}<input name="id2" type="hidden" value="fukuoonsen_fushio_oosakafu"/><div class="con"><a href="./spring_each/" onclick="document.fukuoonsen_fushio_oosakafu.submit(); return false;"><img class="spring_img" src="https://static.yukoyuko.net/images/onsen/onsen_0804_0001.jpg"/></a><p>伏尾温泉</p></div></form><form action="{% url 'appname:springs' %}" method="post" name="ushitakionsen_ushitaki_oosakafu">
{% csrf_token %}<input name="id2" type="hidden" value="ushitakionsen_ushitaki_oosakafu"/><div class="con"><a href="./spring_each/" onclick="document.ushitakionsen_ushitaki_oosakafu.submit(); return false;"><img class="spring_img" src="https://static.yukoyuko.net/images/onsen/onsen_1240_0001.jpg"/></a><p>牛滝温泉</p></div></form><form action="{% url 'appname:springs' %}" method="post" name="kaizukaonsen_kaizuka_oosakafu">
{% csrf_token %}<input name="id2" type="hidden" value="kaizukaonsen_kaizuka_oosakafu"/><div class="con"><a href="./spring_each/" onclick="document.kaizukaonsen_kaizuka_oosakafu.submit(); return false;"><img class="spring_img" src="https://static.yukoyuko.net/images/onsen/onsen_1620_0001.jpg"/></a><p>かいづか温泉</p></div></form><form action="{% url 'appname:springs' %}" method="post" name="soraniwaonsen_soraniwa_oosakafu">
{% csrf_token %}<input name="id2" type="hidden" value="soraniwaonsen_soraniwa_oosakafu"/><div class="con"><a href="./spring_each/" onclick="document.soraniwaonsen_soraniwa_oosakafu.submit(); return false;"><img class="spring_img" src="https://static.yukoyuko.net/images/onsen/onsen_2051_0001.jpg"/></a><p>空庭温泉</p></div></form>
{% endblock content %}